### ISSUE TITLE
Create A sample Profolio For our website

### ISSUE THREAD

**Issue by thecyberbuzz** [thecyberbuzz/anycode#1]
Make Sure You Can Star Our Repo 🌟

**Comment by Digvijay2347** [comment]
Can I Do it ? I am Full stack web developer.

**Comment by thecyberbuzz** [comment]
Ok

**Comment by rahulkamilya** [comment]
Can I ?? @thecyberbuzz

**Comment by Digvijay2347** [comment]
> Ok, Make Sure You Can Star Our Repo 🌟

Please assign it to me . So that i can star the work

**Comment by thecyberbuzz** [comment]
> > Ok, Make Sure You Can Star Our Repo 🌟
> 
> Please assign it to me . So that i can star the work

Ok @Digvijay2347 You R in

**Comment by Digvijay2347** [comment]
> > > Ok, Make Sure You Can Star Our Repo 🌟
> > 
> > 
> > Please assign it to me . So that i can star the work
> 
> Ok @Digvijay2347 You R in

Hey , I have  completed the Given Task. Thank You

**Comment by itssiddhantjain** [comment]
Hello @thecyberbuzz  , please assign this issue to me as I have already worked on this kind of problem in past and has a great experience.

**Comment by thecyberbuzz** [comment]
> Hello @thecyberbuzz , please assign this issue to me as I have already worked on this kind of problem in past and has a great experience.

@itssiddhantjain do it, I'll marge with Hackoctoberfest-accepted

**Comment by sonupachauri02** [comment]
I can di this please give me

**Comment by Ratna2** [comment]
Hello @thecyberbuzz , please assign this issue to me. I want to do that

**Comment by xenetsuke** [comment]
greetings @thecyberbuzz !! kindly assign me this issue as im a MERN developer and created cool animated sites no. of times and really wanna do same for u !!

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with HTML and CSS , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks!

**Comment by itssiddhantjain** [comment]
> > Hello @thecyberbuzz , please assign this issue to me as I have already worked on this kind of problem in past and has a great experience.
> 
> @itssiddhantjain do it, I'll marge with Hackoctoberfest-accepted

@thecyberbuzz I have created aa PR, kindly review and merge it under hacktoberfest

**Comment by itssiddhantjain** [comment]
@thecyberbuzz I have created a PR, kindly review it and merge it under hacktoberfest.

**Comment by itssiddhantjain** [comment]
@thecyberbuzz I have created a PR, kindly review it and merge it under hacktoberfest #89
