### ISSUE TITLE
Create any Sample website I'II Marge for hacktoberfest-accepted

### ISSUE THREAD

**Issue by thecyberbuzz** [thecyberbuzz/anycode#15]
**Things to do**
_Make sure you star🌟 Our Repo, Otherwize your pull request will be not marged !!
Contribute any code (HTML/CSS/JS/REACT....etc)_

**Don't Contribute DSA questions & that kind of things**

**Comment by AkshatJangid787** [comment]
please assign me i will create a best sample website

**Comment by Ratna2** [comment]
please assign me i will create a best sample website

**Comment by exeayush18** [comment]
do assign me too...i also wanted to contribute in this .

**Comment by Ratna2** [comment]
I want do contribution can you assign me @thecyberbuzz

**Comment by AmithBino** [comment]
i will also contribute. A sample Todo webapp with vue js with vuetify

**Comment by AmithBino** [comment]
i will push a sample website code , can u assign me

**Comment by naybyal** [comment]
I wish to contribute. Please assign me.
