### ISSUE TITLE
Create any Sample website I'II Marge 

### ISSUE THREAD

**Issue by thecyberbuzz** [thecyberbuzz/anycode#3]
Make Sure you Star 🌟, Our Repo Before doing any Pull Request

**Comment by thecyberbuzz** [comment]
> what sample website do you want likei have made a full stack todo appp is that okay ???????

Anything like portfolio or any sample pages

**Comment by itssiddhantjain** [comment]
Hello @thecyberbuzz, please assign this issue to me as I have already worked on this kind of problem in past and has a great experience.

**Comment by Pyush-18** [comment]
Hello @thecyberbuzz , I am able to create the fabulous website for you . I want to work on this issue please assign me this issue.

**Comment by Ir786921** [comment]
hey @thecyberbuzz can you please assign me this issue?

**Comment by thecyberbuzz** [comment]
> hey @thecyberbuzz can you please assign me this issue?

Star 🌟, our repo, I'll marge

**Comment by okprateek** [comment]
Hello, @thecyberbuzz. Could you please assign me this issue and let me know if you find a portfolio website useful?
